[theme]
base = "light"
primaryColor = "#003781"
backgroundColor = "#F7FAFF"
secondaryBackgroundColor = "#EAF2FA"
textColor = "#152238"
font = "sans serif"

[server]
headless = true
runOnSave = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
